### ISSUE TITLE
"can-serve not found" error upon running donejs develop with newly-generated plugin.

### ISSUE THREAD

**Issue by marshallswain** [donejs/generator-donejs#100]
I get the following `sh: can-serve: command not found` error when running `donejs develop` after generating a new plugin.
```
Bitovis-MacBook-Pro:mini-calendar Bitovi$ donejs develop

> mini-calendar@0.0.0 develop /Users/Bitovi/Sites/mini-calendar
> can-serve --static --develop --port 8080

sh: can-serve: command not found

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/Users/Bitovi/.npm-packages/bin/npm" "run" "develop"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.14
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! mini-calendar@0.0.0 develop: `can-serve --static --develop --port 8080`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the mini-calendar@0.0.0 develop script 'can-serve --static --develop --port 8080'.
npm ERR! This is most likely a problem with the mini-calendar package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     can-serve --static --develop --port 8080
npm ERR! You can get their info via:
npm ERR!     npm owner ls mini-calendar
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Bitovi/Sites/mini-calendar/npm-debug.log
Error: Command `npm` did not complete successfully
    at ChildProcess.<anonymous> (/Users/Bitovi/Sites/mini-calendar/node_modules/donejs-cli/lib/utils.js:37:23)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

```

**Comment by marshallswain** [comment]
I tried installing done-serve into the devDependencies by doing `npm install done-serve --save-dev` and changing the `develop` script in the package.json to `dev-serve --static --develop --port 8080`.  It looks like the live-reload portion of the server can't start.  I ended up getting the following error:

```
Bitovis-MacBook-Pro:mini-calendar Bitovi$ donejs develop

> mini-calendar@0.0.0 develop /Users/Bitovi/Sites/mini-calendar
> done-serve --static --develop --port 8080

done-serve starting on http://localhost:8080
/Users/Bitovi/Sites/mini-calendar/node_modules/steal-tools/lib/stream/live.js:29
	var port = wss.options.server.address().port;
	                                       ^

TypeError: Cannot read property 'port' of null
    at module.exports (/Users/Bitovi/Sites/mini-calendar/node_modules/steal-tools/lib/stream/live.js:29:41)
    at Object.<anonymous> (/Users/Bitovi/Sites/mini-calendar/node_modules/steal-tools/bin/steal:83:2)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

The rest of the server runs fine.

**Comment by marshallswain** [comment]
I checked in my generated code if you want to see it:
https://github.com/icanjs/mini-calendar

FYI: I changed the port number to 8090.

**Comment by marshallswain** [comment]
donejs --version
0.7.2

**Comment by daffl** [comment]
I'm pretty sure https://github.com/donejs/generator-donejs/issues/57 is related to this

**Comment by marshallswain** [comment]
This was actually a problem with my environment.  The n (nvm clone) module wasn't working correctly and was causing some weird node issues.  I blew away every last byte of node/npm anything and used nvm to install, and now everything works wonderfully.
