### ISSUE TITLE
Can't generate with authorName

### ISSUE THREAD

**Issue by marshallswain** [donejs/generator-donejs#118]
After entering the "Github username or organization", the generator exits with the following error:

```
Bitovis-MacBook-Pro:Sites marshall$ donejs add generator donejs-feathers
Initializing new DoneJS application at /Users/marshall/Sites/donejs-feathers
Installing donejs-cli
donejs-feathers@0.0.0 /Users/marshall/Sites/donejs-feathers
└── donejs-cli@0.9.2  extraneous

? GitHub username or organization 
events.js:154
      throw er; // Unhandled 'error' event
      ^

ReferenceError: /Users/marshall/Sites/donejs-feathers/node_modules/generator-donejs/generator/templates/license.md:3
    1| The MIT License (MIT)
    2| 
 >> 3| Copyright (c) 2015 <%= authorName %>
    4| 
    5| Permission is hereby granted, free of charge, to any person obtaining a copy
    6| of this software and associated documentation files (the "Software"), to deal

authorName is not defined
    at eval (eval at <anonymous> (/Users/marshall/Sites/donejs-feathers/node_modules/ejs/lib/ejs.js:485:12), <anonymous>:11:23)
    at returnedFn (/Users/marshall/Sites/donejs-feathers/node_modules/ejs/lib/ejs.js:514:17)
    at Object.exports.render (/Users/marshall/Sites/donejs-feathers/node_modules/ejs/lib/ejs.js:316:37)
    at copy.process (/Users/marshall/Sites/donejs-feathers/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:14:18)
    at applyProcessingFunc (/Users/marshall/Sites/donejs-feathers/node_modules/mem-fs-editor/lib/actions/copy.js:13:16)
    at EditionInterface.exports._copySingle (/Users/marshall/Sites/donejs-feathers/node_modules/mem-fs-editor/lib/actions/copy.js:51:16)
    at EditionInterface.exports.copy (/Users/marshall/Sites/donejs-feathers/node_modules/mem-fs-editor/lib/actions/copy.js:23:17)
    at EditionInterface.module.exports [as copyTpl] (/Users/marshall/Sites/donejs-feathers/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:12:8)
    at /Users/marshall/Sites/donejs-feathers/node_modules/generator-donejs/generator/index.js:114:15
    at Array.forEach (native)

Error: Command `/Users/marshall/Sites/donejs-feathers/node_modules/.bin/donejs` did not complete successfully
    at ChildProcess.<anonymous> (/Users/marshall/.nvm/versions/node/v5.10.1/lib/node_modules/donejs/lib/utils.js:51:23)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)

Bitovis-MacBook-Pro:Sites marshall$ 

```

**Comment by marshallswain** [comment]
Oops, I already had a project with that name.  It was trying to add it to the project.
