### ISSUE TITLE
Not able to pass arguments to generator plugins

### ISSUE THREAD

**Issue by marshallswain** [donejs/generator-donejs#125]
For the [donejs-connect-model](https://github.com/donejs/donejs-connect-model) generator, I'm unable to use this syntax: `donejs add connect-model [name]`.

Here's the message I get:
```
Bitovis-MacBook-Pro:app-test marshall$ donejs add connect-model schools
Error: You don't seem to have a generator with the name schools installed.
You can see available generators with npm search yeoman-generator and then install them with npm install [name].
To see the 1 registered generators run yo with the `--help` option.
    at Environment.create (/Users/marshall/Sites/app-test/node_modules/yeoman-environment/lib/environment.js:296:7)
    at Environment.run (/Users/marshall/Sites/app-test/node_modules/yeoman-environment/lib/environment.js:364:24)
    at Promise.post (/Users/marshall/Sites/app-test/node_modules/q/q.js:1161:36)
    at Promise.promise.promiseDispatch (/Users/marshall/Sites/app-test/node_modules/q/q.js:788:41)
    at /Users/marshall/Sites/app-test/node_modules/q/q.js:1391:14
    at runSingle (/Users/marshall/Sites/app-test/node_modules/q/q.js:137:13)
    at flush (/Users/marshall/Sites/app-test/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Function.Module.runMain (module.js:449:11)

Error: Command `/Users/marshall/Sites/app-test/node_modules/.bin/donejs` did not complete successfully
    at ChildProcess.<anonymous> (/Users/marshall/.nvm/versions/node/v5.10.1/lib/node_modules/donejs/lib/utils.js:51:23)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
```

**Comment by phillipskevin** [comment]
@marshallswain The syntax  `donejs add connect-model [name]` is used to allow multiple generators inside a single project. This is looking for a `exports.schools` here: https://github.com/donejs/donejs-connect-model/blob/master/lib/index.js#L1. I think for passing arguments, you want to use a prompt.

**Comment by phillipskevin** [comment]
It might actually work if you pass the name of the generator before your arguments. You can try `donejs add connect-model default schools`, but I'm not sure if we've tested this.

**Comment by marshallswain** [comment]
That makes sense.  I'll just remove the option to pass an arg.  Thanks
