### ISSUE TITLE
generating a plugin inside a generated app errors

### ISSUE THREAD

**Issue by leoj3n** [donejs/generator-donejs#220]
__How often can you reproduce it?__

- [x] Always

__Description:__

After generating an app, I `cd`'d into the generated app directory and tried to generate a plugin which resulted in an error.

__Steps to reproduce:__

```
❯ donejs add app donejs-testing && cd donejs-testing && donejs add plugin donejs-plugin-test
Initializing new DoneJS application at /Users/leoj/tmp/donejs-testing
Installing donejs-cli

> spawn-sync@1.0.15 postinstall /Users/leoj/tmp/donejs-testing/node_modules/spawn-sync
> node postinstall

[...]

Just found a `.yo-rc.json` in a parent directory.
Setting the project root at: /Users/leoj/tmp/donejs-testing
? Project main folder src
? Project homepage url
? NPM version used 3
Writing package.json v1.0.1
events.js:160
      throw er; // Unhandled 'error' event
      ^

ReferenceError: /Users/leoj/tmp/donejs-testing/donejs-plugin-test/node_modules/generator-donejs/plugin/templates/CONTRIBUTING.md:5
    3| ## Developing Locally
    4|
 >> 5| This section will walk you through setting up the [repository](https://github.com/<%= githubAccount %>/<%= name %>) on your computer.
    6|
    7| ### Signing up for GitHub
    8|

githubAccount is not defined
    at eval (eval at compile (/Users/leoj/tmp/donejs-testing/donejs-plugin-test/node_modules/ejs/lib/ejs.js:524:12), <anonymous>:13:26)
    at returnedFn (/Users/leoj/tmp/donejs-testing/donejs-plugin-test/node_modules/ejs/lib/ejs.js:555:17)
    at Object.exports.render (/Users/leoj/tmp/donejs-testing/donejs-plugin-test/node_modules/ejs/lib/ejs.js:364:37)
    at process (/Users/leoj/tmp/donejs-testing/donejs-plugin-test/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:12:18)
    at applyProcessingFunc (/Users/leoj/tmp/donejs-testing/donejs-plugin-test/node_modules/mem-fs-editor/lib/actions/copy.js:13:16)
    at EditionInterface.exports._copySingle (/Users/leoj/tmp/donejs-testing/donejs-plugin-test/node_modules/mem-fs-editor/lib/actions/copy.js:63:16)
    at files.forEach.file (/Users/leoj/tmp/donejs-testing/donejs-plugin-test/node_modules/mem-fs-editor/lib/actions/copy.js:50:10)
    at Array.forEach (native)
    at EditionInterface.exports.copy (/Users/leoj/tmp/donejs-testing/donejs-plugin-test/node_modules/mem-fs-editor/lib/actions/copy.js:49:9)
    at EditionInterface.module.exports [as copyTpl] (/Users/leoj/tmp/donejs-testing/donejs-plugin-test/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:10:8)

Error: Command `/Users/leoj/tmp/donejs-testing/donejs-plugin-test/node_modules/.bin/donejs` did not complete successfully
    at ChildProcess.<anonymous> (/Users/leoj/.nvm/versions/node/v6.10.0/lib/node_modules/donejs/lib/utils.js:51:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

Full output: https://gist.github.com/leoj3n/971642fe2c44a1a1139fad0d7639f97d

Notice the ```Just found a `.yo-rc.json` in a parent directory.```.

__Expected results:__

Create the plugin within the app without any issue.

__Actual results:__

Fails with an error!

__Environment:__

| Software                             | Version
| -------------------------- | -------
| donejs -V                            | 1.0.0-alpha.3
| generator-donejs version  | 1.0.0
| node -v                               | v6.10.0
| npm -v                                | 3.10.10
| Operating system              | macOS 10.12.3

**Comment by chasenlehara** [comment]
Holy CLI output Batman! It makes it really hard to read the issue so please only include the relevant parts.

This doesn’t sound like an issue to me. Plugins aren’t supposed to be created within apps. Was there some documentation that led you to believe this would be supported?

**Comment by leoj3n** [comment]
I'd say there was _lack_ of documentation saying that this isn't supported.

The CLI could catch this edge case, and throw a warning, instead of letting it go forward.

As long as DoneJS plugins are meant to be used in DoneJS apps, I expect people will try and generate them within their app like I did here...

Also, why isn't this supported? It seems like a reasonable thing to support to me.

**Comment by chasenlehara** [comment]
I vote 👎 on the CLI handling edge cases like this.

The DoneJS plugin generator is specifically made for creating a brand new project that can be reused in any project (DoneJS or not), not for creating components within a DoneJS app. I don’t think we’re doing a great job of marketing DoneJS apps vs. plugins (SPA vs. code your can reuse), so maybe that would help make this more clear.

Also, I’d really like to see https://github.com/donejs/donejs/issues/682 done so it’s clear what you can add to an app after it’s been generated.
