### ISSUE TITLE
donejs init fails on node 10.

### ISSUE THREAD

**Issue by marshallswain** [donejs/generator-donejs#43]
execSync was added in Node 12.

Problem line is here:
https://github.com/donejs/donejs/blob/master/bin/donejs#L7

```console
var root = path.join(execSync("npm prefix").toString().trim(), 'node_modules')
                     ^
TypeError: undefined is not a function
    at Object.<anonymous> (/Users/marshallthompson/npm/lib/node_modules/donejs/bin/donejs:17:22)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3

```

**Comment by mjstahl** [comment]
Should be closed because of:

https://github.com/donejs/donejs/pull/111
