### ISSUE TITLE
`donejs init donejs-chat` fails in Node .12

### ISSUE THREAD

**Issue by marshallswain** [donejs/generator-donejs#44]
I get the following output when trying to use `donejs init`:

```console
Marshalls-iMac:Sites marshallthompson$ donejs init donejs-chat
Creating folder donejs-chat
Installing generator-donejs
 
> spawn-sync@1.0.13 postinstall /Users/marshallthompson/Sites/donejs-chat/node_modules/generator-donejs/node_modules/yeoman-generator/node_modules/cross-spawn/node_modules/spawn-sync
> node postinstall

generator-donejs@0.2.14 node_modules/generator-donejs
├── q@1.4.1
├── lodash@3.10.1
└── yeoman-generator@0.20.3 (read-chunk@1.0.1, detect-conflict@1.0.0, yeoman-welcome@1.0.1, path-exists@1.0.0, path-is-absolute@1.0.0, yeoman-assert@2.1.0, rimraf@2.4.3, async@1.4.2, text-table@0.2.0, mime@1.3.4, dargs@4.0.1, xdg-basedir@2.0.0, user-home@2.0.0, shelljs@0.5.3, istextorbinary@1.0.2, chalk@1.1.1, debug@2.2.0, nopt@3.0.4, mkdirp@0.5.1, run-async@0.1.0, diff@2.1.2, cli-table@0.3.1, underscore.string@3.2.2, through2@2.0.0, glob@5.0.15, findup-sync@0.2.1, pretty-bytes@2.0.1, dateformat@1.0.11, mem-fs-editor@2.0.4, cross-spawn@2.0.0, github-username@2.0.0, class-extend@0.1.1, download@4.2.1, yeoman-environment@1.2.7, gruntfile-editor@1.0.0, html-wiring@1.2.0, sinon@1.17.1, inquirer@0.8.5)
? Project name: donejs-chat
? Project main folder: src
? Description: 
? Project homepage url: 
? GitHub username or organization: 
? Author's Name: Marshall Thompson
? Author's Email: marshall@creativeideal.net
? Author's Homepage: marshallthompson.net
? Application keywords: 
Installing packages for DoneJS v0.5.0-pre.8
   create package.json
   create readme.md
   create documentjs.json
   create .gitignore
   create build.js
   create src/app.js
   create src/index.stache
   create src/index.md
   create src/index.html
   create src/styles.less
   create src/test.html
   create src/test/test.js
   create src/test/functional.js
   create src/models/fixtures/fixtures.js
   create src/models/test.js
npm WARN package.json donejs-chat@0.0.0 No description
npm WARN package.json donejs-chat@0.0.0 No repository field.
npm ERR! TypeError: undefined is not a function
npm ERR!     at mapToRegistry (/usr/local/lib/node_modules/npm/lib/utils/map-to-registry.js:48:21)
npm ERR!     at getOnceFromRegistry (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:20:3)
npm ERR!     at addNameRange (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:207:3)
npm ERR!     at addNamed (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:50:3)
npm ERR!     at add (/usr/local/lib/node_modules/npm/lib/cache.js:275:11)
npm ERR!     at maybeAt (/usr/local/lib/node_modules/npm/lib/cache.js:354:5)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:344:5
npm ERR!     at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 15.0.0
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "can@~2.3.0-pre.13" "can-connect@~0.2.2" "can-ssr@^0.7.5" "done-autorender@^0.4.0" "done-component@^0.2.0" "done-css@~1.1.8" "generator-donejs@^0.2.14" "jquery@~2.1.4" "steal@^0.12.0-pre.7" "--save"
npm ERR! cwd /Users/marshallthompson/Sites/donejs-chat
npm ERR! node -v v0.12.2
npm ERR! npm -v 1.4.28
npm ERR! TypeError: undefined is not a function
npm ERR!     at mapToRegistry (/usr/local/lib/node_modules/npm/lib/utils/map-to-registry.js:48:21)
npm ERR!     at getOnceFromRegistry (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:20:3)
npm ERR!     at addNameRange (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:207:3)
npm ERR!     at addNamed (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:50:3)
npm ERR!     at add (/usr/local/lib/node_modules/npm/lib/cache.js:275:11)
npm ERR!     at maybeAt (/usr/local/lib/node_modules/npm/lib/cache.js:354:5)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:344:5
npm ERR!     at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 15.0.0
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "can@~2.3.0-pre.13" "can-connect@~0.2.2" "can-ssr@^0.7.5" "done-autorender@^0.4.0" "done-component@^0.2.0" "done-css@~1.1.8" "generator-donejs@^0.2.14" "jquery@~2.1.4" "steal@^0.12.0-pre.7" "--save"
npm ERR! cwd /Users/marshallthompson/Sites/donejs-chat
npm ERR! node -v v0.12.2
npm ERR! npm -v 1.4.28
npm ERR! TypeError: undefined is not a function
npm ERR!     at mapToRegistry (/usr/local/lib/node_modules/npm/lib/utils/map-to-registry.js:48:21)
npm ERR!     at getOnceFromRegistry (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:20:3)
npm ERR!     at addNameRange (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:207:3)
npm ERR!     at addNamed (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:50:3)
npm ERR!     at add (/usr/local/lib/node_modules/npm/lib/cache.js:275:11)
npm ERR!     at maybeAt (/usr/local/lib/node_modules/npm/lib/cache.js:354:5)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:344:5
npm ERR!     at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 15.0.0
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "can@~2.3.0-pre.13" "can-connect@~0.2.2" "can-ssr@^0.7.5" "done-autorender@^0.4.0" "done-component@^0.2.0" "done-css@~1.1.8" "generator-donejs@^0.2.14" "jquery@~2.1.4" "steal@^0.12.0-pre.7" "--save"
npm ERR! cwd /Users/marshallthompson/Sites/donejs-chat
npm ERR! node -v v0.12.2
npm ERR! npm -v 1.4.28
npm ERR! TypeError: undefined is not a function
npm ERR!     at mapToRegistry (/usr/local/lib/node_modules/npm/lib/utils/map-to-registry.js:48:21)
npm ERR!     at getOnceFromRegistry (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:20:3)
npm ERR!     at addNameRange (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:207:3)
npm ERR!     at addNamed (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:50:3)
npm ERR!     at add (/usr/local/lib/node_modules/npm/lib/cache.js:275:11)
npm ERR!     at maybeAt (/usr/local/lib/node_modules/npm/lib/cache.js:354:5)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:344:5
npm ERR!     at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 15.0.0
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "can@~2.3.0-pre.13" "can-connect@~0.2.2" "can-ssr@^0.7.5" "done-autorender@^0.4.0" "done-component@^0.2.0" "done-css@~1.1.8" "generator-donejs@^0.2.14" "jquery@~2.1.4" "steal@^0.12.0-pre.7" "--save"
npm ERR! cwd /Users/marshallthompson/Sites/donejs-chat
npm ERR! node -v v0.12.2
npm ERR! npm -v 1.4.28
npm ERR! TypeError: undefined is not a function
npm ERR!     at mapToRegistry (/usr/local/lib/node_modules/npm/lib/utils/map-to-registry.js:48:21)
npm ERR!     at getOnceFromRegistry (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:20:3)
npm ERR!     at addNameRange (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:207:3)
npm ERR!     at addNamed (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:50:3)
npm ERR!     at add (/usr/local/lib/node_modules/npm/lib/cache.js:275:11)
npm ERR!     at maybeAt (/usr/local/lib/node_modules/npm/lib/cache.js:354:5)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:344:5
npm ERR!     at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 15.0.0
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "can@~2.3.0-pre.13" "can-connect@~0.2.2" "can-ssr@^0.7.5" "done-autorender@^0.4.0" "done-component@^0.2.0" "done-css@~1.1.8" "generator-donejs@^0.2.14" "jquery@~2.1.4" "steal@^0.12.0-pre.7" "--save"
npm ERR! cwd /Users/marshallthompson/Sites/donejs-chat
npm ERR! node -v v0.12.2
npm ERR! npm -v 1.4.28
npm ERR! TypeError: undefined is not a function
npm ERR!     at mapToRegistry (/usr/local/lib/node_modules/npm/lib/utils/map-to-registry.js:48:21)
npm ERR!     at getOnceFromRegistry (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:20:3)
npm ERR!     at addNameRange (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:207:3)
npm ERR!     at addNamed (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:50:3)
npm ERR!     at add (/usr/local/lib/node_modules/npm/lib/cache.js:275:11)
npm ERR!     at maybeAt (/usr/local/lib/node_modules/npm/lib/cache.js:354:5)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:344:5
npm ERR!     at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 15.0.0
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "can@~2.3.0-pre.13" "can-connect@~0.2.2" "can-ssr@^0.7.5" "done-autorender@^0.4.0" "done-component@^0.2.0" "done-css@~1.1.8" "generator-donejs@^0.2.14" "jquery@~2.1.4" "steal@^0.12.0-pre.7" "--save"
npm ERR! cwd /Users/marshallthompson/Sites/donejs-chat
npm ERR! node -v v0.12.2
npm ERR! npm -v 1.4.28
npm ERR! TypeError: undefined is not a function
npm ERR!     at mapToRegistry (/usr/local/lib/node_modules/npm/lib/utils/map-to-registry.js:48:21)
npm ERR!     at getOnceFromRegistry (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:20:3)
npm ERR!     at addNameRange (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:207:3)
npm ERR!     at addNamed (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:50:3)
npm ERR!     at add (/usr/local/lib/node_modules/npm/lib/cache.js:275:11)
npm ERR!     at maybeAt (/usr/local/lib/node_modules/npm/lib/cache.js:354:5)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:344:5
npm ERR!     at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 15.0.0
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "can@~2.3.0-pre.13" "can-connect@~0.2.2" "can-ssr@^0.7.5" "done-autorender@^0.4.0" "done-component@^0.2.0" "done-css@~1.1.8" "generator-donejs@^0.2.14" "jquery@~2.1.4" "steal@^0.12.0-pre.7" "--save"
npm ERR! cwd /Users/marshallthompson/Sites/donejs-chat
npm ERR! node -v v0.12.2
npm ERR! npm -v 1.4.28
npm ERR! TypeError: undefined is not a function
npm ERR!     at mapToRegistry (/usr/local/lib/node_modules/npm/lib/utils/map-to-registry.js:48:21)
npm ERR!     at getOnceFromRegistry (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:20:3)
npm ERR!     at addNameRange (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:207:3)
npm ERR!     at addNamed (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:50:3)
npm ERR!     at add (/usr/local/lib/node_modules/npm/lib/cache.js:275:11)
npm ERR!     at maybeAt (/usr/local/lib/node_modules/npm/lib/cache.js:354:5)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:344:5
npm ERR!     at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 15.0.0
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "can@~2.3.0-pre.13" "can-connect@~0.2.2" "can-ssr@^0.7.5" "done-autorender@^0.4.0" "done-component@^0.2.0" "done-css@~1.1.8" "generator-donejs@^0.2.14" "jquery@~2.1.4" "steal@^0.12.0-pre.7" "--save"
npm ERR! cwd /Users/marshallthompson/Sites/donejs-chat
npm ERR! node -v v0.12.2
npm ERR! npm -v 1.4.28
npm ERR! TypeError: undefined is not a function
npm ERR!     at mapToRegistry (/usr/local/lib/node_modules/npm/lib/utils/map-to-registry.js:48:21)
npm ERR!     at getOnceFromRegistry (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:20:3)
npm ERR!     at addNameRange (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:207:3)
npm ERR!     at addNamed (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:50:3)
npm ERR!     at add (/usr/local/lib/node_modules/npm/lib/cache.js:275:11)
npm ERR!     at maybeAt (/usr/local/lib/node_modules/npm/lib/cache.js:354:5)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:344:5
npm ERR!     at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 15.0.0
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "can@~2.3.0-pre.13" "can-connect@~0.2.2" "can-ssr@^0.7.5" "done-autorender@^0.4.0" "done-component@^0.2.0" "done-css@~1.1.8" "generator-donejs@^0.2.14" "jquery@~2.1.4" "steal@^0.12.0-pre.7" "--save"
npm ERR! cwd /Users/marshallthompson/Sites/donejs-chat
npm ERR! node -v v0.12.2
npm ERR! npm -v 1.4.28
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/marshallthompson/Sites/donejs-chat/npm-debug.log
npm ERR! not ok code 0
npm WARN package.json donejs-chat@0.0.0 No description
npm WARN package.json donejs-chat@0.0.0 No repository field.
npm ERR! TypeError: undefined is not a function
npm ERR!     at mapToRegistry (/usr/local/lib/node_modules/npm/lib/utils/map-to-registry.js:48:21)
npm ERR!     at getOnceFromRegistry (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:20:3)
npm ERR!     at addNameRange (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:207:3)
npm ERR!     at addNamed (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:50:3)
npm ERR!     at add (/usr/local/lib/node_modules/npm/lib/cache.js:275:11)
npm ERR!     at maybeAt (/usr/local/lib/node_modules/npm/lib/cache.js:354:5)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:344:5
npm ERR!     at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 15.0.0
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "documentjs@^0.3.0" "donejs-deploy@^0.2.0" "funcunit@~3.0.0" "steal-qunit@^0.1.1" "steal-tools@^0.12.0-pre.3" "testee@^0.2.0" "--save-dev"
npm ERR! cwd /Users/marshallthompson/Sites/donejs-chat
npm ERR! node -v v0.12.2
npm ERR! npm -v 1.4.28
npm ERR! TypeError: undefined is not a function
npm ERR!     at mapToRegistry (/usr/local/lib/node_modules/npm/lib/utils/map-to-registry.js:48:21)
npm ERR!     at getOnceFromRegistry (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:20:3)
npm ERR!     at addNameRange (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:207:3)
npm ERR!     at addNamed (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:50:3)
npm ERR!     at add (/usr/local/lib/node_modules/npm/lib/cache.js:275:11)
npm ERR!     at maybeAt (/usr/local/lib/node_modules/npm/lib/cache.js:354:5)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:344:5
npm ERR!     at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 15.0.0
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "documentjs@^0.3.0" "donejs-deploy@^0.2.0" "funcunit@~3.0.0" "steal-qunit@^0.1.1" "steal-tools@^0.12.0-pre.3" "testee@^0.2.0" "--save-dev"
npm ERR! cwd /Users/marshallthompson/Sites/donejs-chat
npm ERR! node -v v0.12.2
npm ERR! npm -v 1.4.28
npm ERR! TypeError: undefined is not a function
npm ERR!     at mapToRegistry (/usr/local/lib/node_modules/npm/lib/utils/map-to-registry.js:48:21)
npm ERR!     at getOnceFromRegistry (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:20:3)
npm ERR!     at addNameRange (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:207:3)
npm ERR!     at addNamed (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:50:3)
npm ERR!     at add (/usr/local/lib/node_modules/npm/lib/cache.js:275:11)
npm ERR!     at maybeAt (/usr/local/lib/node_modules/npm/lib/cache.js:354:5)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:344:5
npm ERR!     at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 15.0.0
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "documentjs@^0.3.0" "donejs-deploy@^0.2.0" "funcunit@~3.0.0" "steal-qunit@^0.1.1" "steal-tools@^0.12.0-pre.3" "testee@^0.2.0" "--save-dev"
npm ERR! cwd /Users/marshallthompson/Sites/donejs-chat
npm ERR! node -v v0.12.2
npm ERR! npm -v 1.4.28
npm ERR! TypeError: undefined is not a function
npm ERR!     at mapToRegistry (/usr/local/lib/node_modules/npm/lib/utils/map-to-registry.js:48:21)
npm ERR!     at getOnceFromRegistry (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:20:3)
npm ERR!     at addNameRange (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:207:3)
npm ERR!     at addNamed (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:50:3)
npm ERR!     at add (/usr/local/lib/node_modules/npm/lib/cache.js:275:11)
npm ERR!     at maybeAt (/usr/local/lib/node_modules/npm/lib/cache.js:354:5)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:344:5
npm ERR!     at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 15.0.0
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "documentjs@^0.3.0" "donejs-deploy@^0.2.0" "funcunit@~3.0.0" "steal-qunit@^0.1.1" "steal-tools@^0.12.0-pre.3" "testee@^0.2.0" "--save-dev"
npm ERR! cwd /Users/marshallthompson/Sites/donejs-chat
npm ERR! node -v v0.12.2
npm ERR! npm -v 1.4.28
npm ERR! TypeError: undefined is not a function
npm ERR!     at mapToRegistry (/usr/local/lib/node_modules/npm/lib/utils/map-to-registry.js:48:21)
npm ERR!     at getOnceFromRegistry (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:20:3)
npm ERR!     at addNameRange (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:207:3)
npm ERR!     at addNamed (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:50:3)
npm ERR!     at add (/usr/local/lib/node_modules/npm/lib/cache.js:275:11)
npm ERR!     at maybeAt (/usr/local/lib/node_modules/npm/lib/cache.js:354:5)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:344:5
npm ERR!     at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 15.0.0
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "documentjs@^0.3.0" "donejs-deploy@^0.2.0" "funcunit@~3.0.0" "steal-qunit@^0.1.1" "steal-tools@^0.12.0-pre.3" "testee@^0.2.0" "--save-dev"
npm ERR! cwd /Users/marshallthompson/Sites/donejs-chat
npm ERR! node -v v0.12.2
npm ERR! npm -v 1.4.28
npm ERR! TypeError: undefined is not a function
npm ERR!     at mapToRegistry (/usr/local/lib/node_modules/npm/lib/utils/map-to-registry.js:48:21)
npm ERR!     at getOnceFromRegistry (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:20:3)
npm ERR!     at addNameRange (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:207:3)
npm ERR!     at addNamed (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:50:3)
npm ERR!     at add (/usr/local/lib/node_modules/npm/lib/cache.js:275:11)
npm ERR!     at maybeAt (/usr/local/lib/node_modules/npm/lib/cache.js:354:5)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:344:5
npm ERR!     at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 15.0.0
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "documentjs@^0.3.0" "donejs-deploy@^0.2.0" "funcunit@~3.0.0" "steal-qunit@^0.1.1" "steal-tools@^0.12.0-pre.3" "testee@^0.2.0" "--save-dev"
npm ERR! cwd /Users/marshallthompson/Sites/donejs-chat
npm ERR! node -v v0.12.2
npm ERR! npm -v 1.4.28
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/marshallthompson/Sites/donejs-chat/npm-debug.log
npm ERR! not ok code 0
```

**Comment by daffl** [comment]
I'll add 0.12 to the list and see if it passes. I guess Travis runs it on 4.0 at the moment.

**Comment by marshallswain** [comment]
There must have been something wrong with my machine.  I can't reproduce this issue, now.  Closing.
