### ISSUE TITLE
supermodel generator fails in v0.6.9

### ISSUE THREAD

**Issue by Alfredo-Delgado** [donejs/generator-donejs#85]
OS X, node v0.12.7:
```shell
$ donejs add supermodel message
? What is the URL endpoint? http://chat.donejs.com/api/messages
? What is the property name of the id? id
events.js:85
      throw er; // Unhandled 'error' event
            ^
TypeError: undefined is not a function
    at module.exports.generators.Base.extend.writing (/Users/adelgado/Documents/src/js/bitovi/donejs-chat/node_modules/generator-donejs/supermodel/index.js:72:20)
    at /Users/adelgado/Documents/src/js/bitovi/donejs-chat/node_modules/generator-donejs/node_modules/yeoman-generator/lib/base.js:429:16
    at processImmediate [as _immediateCallback] (timers.js:367:17)
```

**Comment by Alfredo-Delgado** [comment]
ubuntu, node v4.3.1:
```shell
$ donejs add supermodel message
? What is the URL endpoint? http://chat.donejs.com/api/messages
? What is the property name of the id? id
events.js:141
      throw er; // Unhandled 'error' event
      ^

TypeError: _.upperFirst is not a function
    at module.exports.generators.Base.extend.writing (/home/adelgado/src/donejs-chat/node_modules/generator-donejs/supermodel/index.js:72:20)
    at /home/adelgado/src/donejs-chat/node_modules/generator-donejs/node_modules/yeoman-generator/lib/base.js:429:16
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by justinbmeyer** [comment]
Can you check if this is an underscore or lodash version issue?
