### ISSUE TITLE
Error when generating a plugin

### ISSUE THREAD

**Issue by marshallswain** [donejs/generator-donejs#99]
I encountered the following error while starting a new plugin this morning:
```
Bitovis-MacBook-Pro:Sites Bitovi$ donejs plugin
Initializing new DoneJS application at /Users/Bitovi/Sites
Installing donejs-cli
 
> spawn-sync@1.0.15 postinstall /Users/Bitovi/Sites/node_modules/donejs-cli/node_modules/yeoman-generator/node_modules/cross-spawn/node_modules/spawn-sync
> node postinstall

donejs-cli@0.7.2 node_modules/donejs-cli
├── q@1.4.1
├── steal-platform@0.0.4
├── commander@2.9.0 (graceful-readlink@1.0.1)
├── debug@2.2.0 (ms@0.7.1)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── cross-spawn-async@2.1.9 (lru-cache@4.0.0, which@1.2.4)
├── yeoman-environment@1.5.2 (escape-string-regexp@1.0.5, log-symbols@1.0.2, grouped-queue@0.3.2, text-table@0.2.0, diff@2.2.2, untildify@2.1.0, chalk@1.1.1, mem-fs@1.1.2, inquirer@0.11.4, globby@4.0.0, lodash@3.10.1)
└── yeoman-generator@0.20.3 (detect-conflict@1.0.0, read-chunk@1.0.1, yeoman-assert@2.1.1, yeoman-welcome@1.0.1, path-exists@1.0.0, path-is-absolute@1.0.0, async@1.5.2, mime@1.3.4, text-table@0.2.0, class-extend@0.1.2, dargs@4.1.0, diff@2.2.2, istextorbinary@1.0.2, user-home@2.0.0, xdg-basedir@2.0.0, nopt@3.0.6, shelljs@0.5.3, cli-table@0.3.1, run-async@0.1.0, chalk@1.1.1, through2@2.0.1, glob@5.0.15, findup-sync@0.2.1, rimraf@2.5.2, mem-fs-editor@2.2.0, cross-spawn@2.1.5, underscore.string@3.3.4, dateformat@1.0.12, github-username@2.1.0, pretty-bytes@2.0.1, gruntfile-editor@1.1.0, html-wiring@1.2.0, lodash@3.10.1, inquirer@0.8.5, download@4.4.3, sinon@1.17.3)
Installing generator-donejs
 
> spawn-sync@1.0.15 postinstall /Users/Bitovi/Sites/node_modules/generator-donejs/node_modules/yeoman-generator/node_modules/cross-spawn/node_modules/spawn-sync
> node postinstall

generator-donejs@0.7.7 node_modules/generator-donejs
├── q@1.4.1
├── semver@5.1.0
├── lodash@3.10.1
├── validate-npm-package-name@2.2.2 (builtins@0.0.7)
├── lodash.upperfirst@4.1.2 (lodash.tostring@4.1.2)
└── yeoman-generator@0.20.3 (read-chunk@1.0.1, detect-conflict@1.0.0, yeoman-assert@2.1.1, yeoman-welcome@1.0.1, path-exists@1.0.0, path-is-absolute@1.0.0, async@1.5.2, mime@1.3.4, text-table@0.2.0, xdg-basedir@2.0.0, user-home@2.0.0, diff@2.2.2, istextorbinary@1.0.2, class-extend@0.1.2, dargs@4.1.0, debug@2.2.0, nopt@3.0.6, shelljs@0.5.3, cli-table@0.3.1, run-async@0.1.0, mkdirp@0.5.1, chalk@1.1.1, through2@2.0.1, glob@5.0.15, findup-sync@0.2.1, rimraf@2.5.2, mem-fs-editor@2.2.0, yeoman-environment@1.5.2, underscore.string@3.3.4, cross-spawn@2.1.5, github-username@2.1.0, pretty-bytes@2.0.1, dateformat@1.0.12, html-wiring@1.2.0, gruntfile-editor@1.1.0, inquirer@0.8.5, download@4.4.3, sinon@1.17.3)
? Project name mini-calendar
? Project main folder src
? Description A mini calendar component for CanJS.
? Project homepage url https://github.com/icanjs/mini-calendar
? GitHub username or organization icanjs
? Author's Name Marshall Thompson
? Author's Email marshall@creativeideal.net
? Author's Homepage https://github.com/icanjs
? Application keywords canjs,can,component,calendar,dates
? NPM version used 2
Writing package.json v0.7.2
   create package.json
   create build.js
   create .editorconfig
   create .jshintrc
   create .npmignore
   create .travis.yml
   create documentjs.json
   create readme.md
   create .gitignore
   create src/test/test.html
   create src/test/test.js
   create src/mini-calendar_test.js
   create src/mini-calendar.js
   create src/mini-calendar.md
WARN engine testee@0.2.5: wanted: {"node":"~0.10"} (current: {"node":"4.2.6","npm":"2.14.14"})
WARN engine steal-tools@0.14.1: wanted: {"node":"0.10.x - 0.12.x || ^3.0.0"} (current: {"node":"4.2.6","npm":"2.14.14"})
WARN engine miner@0.2.1: wanted: {"node":"~0.10"} (current: {"node":"4.2.6","npm":"2.14.14"})
WARN engine launchpad@0.5.1: wanted: {"node":"^0.12"} (current: {"node":"4.2.6","npm":"2.14.14"})
WARN engine steal-tools@0.13.6: wanted: {"node":"0.10.x - 0.12.x || ^3.0.0"} (current: {"node":"4.2.6","npm":"2.14.14"})
 
> dtrace-provider@0.6.0 install /Users/Bitovi/Sites/node_modules/testee/node_modules/launchpad/node_modules/restify/node_modules/dtrace-provider
> node scripts/install.js

WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"4.2.6","npm":"2.14.14"})
WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"4.2.6","npm":"2.14.14"})
WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"4.2.6","npm":"2.14.14"})
WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"4.2.6","npm":"2.14.14"})
WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"4.2.6","npm":"2.14.14"})
WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"4.2.6","npm":"2.14.14"})
WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"4.2.6","npm":"2.14.14"})
WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"4.2.6","npm":"2.14.14"})
WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"4.2.6","npm":"2.14.14"})
WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"4.2.6","npm":"2.14.14"})
 
> fsevents@1.0.8 install /Users/Bitovi/Sites/node_modules/documentjs/node_modules/chokidar/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "/Users/Bitovi/Sites/node_modules/documentjs/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v46-darwin-x64/fse.node" is installed via remote
 
> fsevents@1.0.8 install /Users/Bitovi/Sites/node_modules/steal-tools/node_modules/chokidar/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

[fsevents] Success: "/Users/Bitovi/Sites/node_modules/steal-tools/node_modules/chokidar/node_modules/fsevents/lib/binding/Release/node-v46-darwin-x64/fse.node" is installed via remote
\
> documentjs@0.4.2 postinstall /Users/Bitovi/Sites/node_modules/documentjs
> install-engine-dependencies

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/Users/Bitovi/.npm-packages/bin/npm" "--loglevel" "error" "install"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.14
npm ERR! file /Users/Bitovi/.npm/underscore/1.8.3/package/package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! No data, empty input at 1:1
npm ERR! 
npm ERR! ^
npm ERR! File: /Users/Bitovi/.npm/underscore/1.8.3/package/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Bitovi/Sites/npm-debug.log
events.js:146
      throw err;
      ^

Error: Uncaught, unspecified "error" event. (1)
    at emit (events.js:144:17)
    at ChildProcess.done (/Users/Bitovi/Sites/node_modules/generator-donejs/node_modules/yeoman-generator/lib/base.js:414:16)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:821:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
Error: Command `node` did not complete successfully
    at ChildProcess.<anonymous> (/Users/Bitovi/.npm-packages/lib/node_modules/donejs/lib/utils.js:45:23)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

**Comment by marshallswain** [comment]
I missed the plugin name argument, so it generated the plugin directly in my Sites folder.  When I added the plugin name, it worked fine.
